/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { DrinkMenuItem, SizeOption, ExtraOption } from '../types/cafe';

// 1. 음료 메뉴 목록
export const DRINK_MENU: DrinkMenuItem[] = [
  { id: 'americano', name: '아메리카노', price: 3500, emoji: '☕', description: '깊고 깔끔한 원두 본연의 풍미' },
  { id: 'latte', name: '카페라떼', price: 4000, emoji: '🥛', description: '부드러운 스팀밀크와 에스프레소의 조화' },
  { id: 'mocha', name: '카페모카', price: 4500, emoji: '🍫', description: '달콤한 초콜릿과 진한 커피의 만남' },
  { id: 'vanilla-latte', name: '바닐라라떼', price: 4500, emoji: '🍦', description: '은은한 천연 바닐라 향 가득' },
  { id: 'greentea-latte', name: '녹차라떼', price: 4500, emoji: '🍵', description: '제주 유기농 말차의 부드럽고 쌉싸름한 맛' },
];

// 2. 사이즈 옵션 (M 사이즈가 기본값)
export const SIZE_OPTIONS: SizeOption[] = [
  { id: 'S', name: 'S', extraPrice: 0 },
  { id: 'M', name: 'M', extraPrice: 500 },
  { id: 'L', name: 'L', extraPrice: 1000 },
];

// 3. 추가 옵션 목록
export const EXTRA_OPTIONS: ExtraOption[] = [
  { id: 'shot', name: '샷 추가', extraPrice: 500 },
  { id: 'cream', name: '크림 추가', extraPrice: 500 },
  { id: 'syrup', name: '시럽 추가', extraPrice: 300 },
  { id: 'decaf', name: '디카페인', extraPrice: 0 },
];

// 기본 주문서 폼 상태값
export const INITIAL_FORM_DATA = {
  customerName: '',
  phoneNumber: '',
  selectedDrinkId: '',
  size: 'M' as const,
  selectedOptions: [] as string[],
  quantity: 1,
  requests: '',
};

// 4. Supabase SQL 쿼리문 (테이블 생성 및 가짜 데이터 1건 삽입)
export const SUPABASE_SQL_CREATE_TABLE = `-- ============================================================
-- [바이브 카페] Supabase SQL Editor용 테이블 생성 쿼리문
-- 테이블명: cafe_menu (주문서 항목 반영)
-- ============================================================

-- 1. cafe_menu 테이블 생성
CREATE TABLE IF NOT EXISTS public.cafe_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 고유 주문 ID
    customer_name VARCHAR(100) NOT NULL,                    -- 주문자 이름 (필수)
    phone_number VARCHAR(20),                               -- 전화번호 (선택)
    drink_name VARCHAR(100) NOT NULL,                       -- 선택한 음료명 (필수)
    size VARCHAR(10) NOT NULL DEFAULT 'M',                  -- 음료 사이즈 (S, M, L)
    extra_options TEXT[],                                   -- 추가 옵션 배열 (예: ['샷 추가', '크림 추가'])
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 1 AND quantity <= 10), -- 수량 (1~10)
    requests TEXT,                                          -- 고객 요청사항 (textarea)
    unit_price INTEGER NOT NULL,                            -- 음료 1잔당 단가 (원)
    total_price INTEGER NOT NULL,                           -- 총 주문 예상 금액 (원)
    status VARCHAR(20) DEFAULT '접수완료',                   -- 주문 처리 상태 (접수완료, 제조중, 픽업대기, 완료)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL -- 주문 생성 일시
);

-- 2. 테이블 및 컬럼 설명 주석(COMMENT) 추가
COMMENT ON TABLE public.cafe_menu IS '바이브 카페 고객 주문 및 메뉴 주문서 테이블';
COMMENT ON COLUMN public.cafe_menu.customer_name IS '주문자 고객명';
COMMENT ON COLUMN public.cafe_menu.phone_number IS '주문자 연락처';
COMMENT ON COLUMN public.cafe_menu.drink_name IS '선택한 카페 음료명';
COMMENT ON COLUMN public.cafe_menu.size IS '컵 사이즈 (S, M, L)';
COMMENT ON COLUMN public.cafe_menu.extra_options IS '선택된 추가 옵션 리스트';
COMMENT ON COLUMN public.cafe_menu.quantity IS '주문 수량 (1~10)';
COMMENT ON COLUMN public.cafe_menu.requests IS '고객 특별 요청사항';
COMMENT ON COLUMN public.cafe_menu.unit_price IS '옵션 포함 음료 1잔 가격';
COMMENT ON COLUMN public.cafe_menu.total_price IS '최종 결제 금액 (단가 * 수량)';
COMMENT ON COLUMN public.cafe_menu.created_at IS '주문 접수 일시';

-- 3. Row Level Security (RLS) 활성화 (Supabase 권장)
ALTER TABLE public.cafe_menu ENABLE ROW LEVEL SECURITY;

-- 4. 모든 사용자 읽기/쓰기 허용 정책 생성 (공개 주문용)
CREATE POLICY "누구나 주문 등록 가능" 
ON public.cafe_menu 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "누구나 주문 내역 조회 가능" 
ON public.cafe_menu 
FOR SELECT 
USING (true);`;

export const SUPABASE_SQL_INSERT_MOCK = `-- ============================================================
-- [바이브 카페] 테스트용 가짜 데이터 1건 삽입 (INSERT 쿼리문)
-- ============================================================

INSERT INTO public.cafe_menu (
    customer_name,
    phone_number,
    drink_name,
    size,
    extra_options,
    quantity,
    requests,
    unit_price,
    total_price,
    status
) VALUES (
    '홍길동',
    '010-1234-5678',
    '카페라떼',
    'M',
    ARRAY['샷 추가'],
    1,
    '얼음 조금만 넣어주세요, 종이 빨대로 부탁드립니다!',
    5000,
    5000,
    '접수완료'
);

-- 방금 삽입된 데이터 확인 쿼리
SELECT * FROM public.cafe_menu ORDER BY id DESC LIMIT 1;`;
